// apps/admin/src/views/Dashboard.vue
<template>
  <div class="dashboard">
    <el-row :gutter="20" class="stat-row">
      <el-col :span="4" v-for="stat in stats" :key="stat.label">
        <el-card shadow="hover" class="stat-card">
          <div class="stat-icon" :style="{ background: stat.color }">
            <el-icon :size="28"><component :is="stat.icon" /></el-icon>
          </div>
          <div class="stat-info">
            <div class="stat-value">{{ stat.value }}</div>
            <div class="stat-label">{{ stat.label }}</div>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <el-row :gutter="20" style="margin-top: 20px;">
      <el-col :span="12">
        <el-card>
          <template #header>
            <span style="font-weight: 700;">最近订单</span>
          </template>
          <el-table :data="recentOrders" stripe size="small">
            <el-table-column prop="orderNo" label="订单号" />
            <el-table-column label="套餐">
              <template #default="{ row }">
                {{ row.package?.country?.name }} {{ row.package?.gb }}GB
              </template>
            </el-table-column>
            <el-table-column prop="price" label="金额">
              <template #default="{ row }">¥{{ row.price }}</template>
            </el-table-column>
            <el-table-column prop="status" label="状态">
              <template #default="{ row }">
                <el-tag :type="row.status === 'paid' ? 'success' : 'warning'" size="small">
                  {{ row.status === 'paid' ? '已支付' : '待支付' }}
                </el-tag>
              </template>
            </el-table-column>
          </el-table>
        </el-card>
      </el-col>
      <el-col :span="12">
        <el-card>
          <template #header>
            <span style="font-weight: 700;">最近 eSIM</span>
          </template>
          <el-table :data="recentEsims" stripe size="small">
            <el-table-column label="国家">
              <template #default="{ row }">
                {{ row.order?.package?.country?.flag }} {{ row.order?.package?.country?.name }}
              </template>
            </el-table-column>
            <el-table-column prop="iccid" label="ICCID" show-overflow-tooltip />
            <el-table-column prop="status" label="状态">
              <template #default="{ row }">
                <el-tag :type="row.status === 'activated' ? 'success' : 'info'" size="small">
                  {{ row.status === 'activated' ? '已激活' : '待激活' }}
                </el-tag>
              </template>
            </el-table-column>
          </el-table>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { adminApi } from '../api';

const stats = ref([
  { label: '国家/地区', value: 0, icon: 'MapLocation', color: '#0EA5E9' },
  { label: '套餐数量', value: 0, icon: 'ShoppingCart', color: '#FF7A59' },
  { label: '总订单', value: 0, icon: 'Document', color: '#14B8A6' },
  { label: '已支付', value: 0, icon: 'CircleCheck', color: '#10B981' },
  { label: 'eSIM 总数', value: 0, icon: 'Iphone', color: '#8B5CF6' },
  { label: '总收入', value: '¥0', icon: 'Money', color: '#F59E0B' },
]);

const recentOrders = ref([]);
const recentEsims = ref([]);

onMounted(async () => {
  try {
    const res = await adminApi.getDashboard();
    const s = res.data.data.stats;
    stats.value[0].value = s.countryCount;
    stats.value[1].value = s.packageCount;
    stats.value[2].value = s.orderCount;
    stats.value[3].value = s.paidOrders;
    stats.value[4].value = s.esimCount;
    stats.value[5].value = `¥${s.totalRevenue.toFixed(1)}`;

    const ordersRes = await adminApi.getOrders();
    recentOrders.value = ordersRes.data.data.orders.slice(0, 5);

    const esimsRes = await adminApi.getEsims();
    recentEsims.value = esimsRes.data.data.esims.slice(0, 5);
  } catch (e) {
    console.error(e);
  }
});
</script>

<style scoped>
.stat-row {
  margin-bottom: 0;
}

.stat-card {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 8px;
}

.stat-icon {
  width: 56px;
  height: 56px;
  border-radius: 14px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  flex-shrink: 0;
}

.stat-info {
  flex: 1;
}

.stat-value {
  font-size: 26px;
  font-weight: 800;
  color: #0F2A43;
}

.stat-label {
  font-size: 13px;
  color: #93AFC8;
  margin-top: 4px;
}
</style>

// apps/admin/src/app/(admin)/dashboard/page.tsx
'use client';

import { useEffect, useState } from 'react';
import {
  Globe,
  Package as PackageIcon,
  ReceiptText,
  CircleCheck,
  Smartphone,
  Wallet,
} from 'lucide-react';
import { toast } from 'sonner';
import { StatCard } from '@/components/StatCard';
import { EmptyState } from '@/components/EmptyState';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { adminApi, unwrap, getErrorMessage, type DashboardStats, type Order, type Esim } from '@/api';

const ACCENT = ['#6f8f8b', '#c58f6a', '#7a95a8'];

function StatBadge({ status }: { status: string }) {
  if (status === 'paid') return <Badge variant="success">已支付</Badge>;
  if (status === 'refunded') return <Badge variant="info">已退款</Badge>;
  return <Badge variant="warning">待支付</Badge>;
}

export default function DashboardPage() {
  const [stats, setStats] = useState<DashboardStats>({
    countryCount: 0,
    packageCount: 0,
    orderCount: 0,
    paidOrders: 0,
    esimCount: 0,
    totalRevenue: 0,
  });
  const [orders, setOrders] = useState<Order[]>([]);
  const [esims, setEsims] = useState<Esim[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        const [s, o, e] = await Promise.all([
          adminApi.getDashboard(),
          adminApi.getOrders(),
          adminApi.getEsims(),
        ]);
        setStats(unwrap<DashboardStats>(s).data);
        setOrders(unwrap<{ orders: Order[] }>(o).data.orders.slice(0, 5));
        setEsims(unwrap<{ esims: Esim[] }>(e).data.esims.slice(0, 5));
      } catch (err) {
        toast.error(getErrorMessage(err, '仪表盘数据加载失败'));
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const cardDefs = [
    { label: '国家/地区', value: stats.countryCount, icon: <Globe size={22} />, color: ACCENT[0], delay: 0 },
    { label: '套餐数量', value: stats.packageCount, icon: <PackageIcon size={22} />, color: '#c58f6a', delay: 40 },
    { label: '总订单', value: stats.orderCount, icon: <ReceiptText size={22} />, color: '#7a95a8', delay: 80 },
    { label: '已支付', value: stats.paidOrders, icon: <CircleCheck size={22} />, color: '#5f8f76', delay: 120 },
    { label: 'eSIM 总数', value: stats.esimCount, icon: <Smartphone size={22} />, color: '#a68bb8', delay: 160 },
    { label: '总收入', value: `¥${Number(stats.totalRevenue || 0).toFixed(1)}`, icon: <Wallet size={22} />, color: '#d4a05f', delay: 200 },
  ];

  return (
    <div className="animate-fade-up space-y-5">
      <div className="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-6">
        {cardDefs.map((c) => (
          <StatCard key={c.label} {...c} />
        ))}
      </div>

      <div className="grid gap-5 lg:grid-cols-2">
        <Card className="border-transparent bg-white/70 backdrop-blur-sm">
          <CardHeader className="pb-3">
            <CardTitle className="text-[15px] text-ink">最近订单</CardTitle>
          </CardHeader>
          <CardContent>
            {orders.length === 0 && !loading ? (
              <EmptyState title="暂无订单" />
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>订单号</TableHead>
                    <TableHead>套餐</TableHead>
                    <TableHead>金额</TableHead>
                    <TableHead>状态</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {orders.map((o) => (
                    <TableRow key={o.id}>
                      <TableCell className="font-mono text-[12.5px]">{o.orderNo}</TableCell>
                      <TableCell>
                        {o.package?.country?.flag} {o.package?.country?.name} {o.package?.gb}GB
                      </TableCell>
                      <TableCell>¥{o.price}</TableCell>
                      <TableCell>
                        <StatBadge status={o.status} />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>

        <Card className="border-transparent bg-white/70 backdrop-blur-sm">
          <CardHeader className="pb-3">
            <CardTitle className="text-[15px] text-ink">最近 eSIM</CardTitle>
          </CardHeader>
          <CardContent>
            {esims.length === 0 && !loading ? (
              <EmptyState title="暂无 eSIM" />
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>国家</TableHead>
                    <TableHead>ICCID</TableHead>
                    <TableHead>状态</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {esims.map((e) => (
                    <TableRow key={e.id}>
                      <TableCell>
                        {e.order?.package?.country?.flag} {e.order?.package?.country?.name}
                      </TableCell>
                      <TableCell className="font-mono text-[12.5px]">{e.iccid}</TableCell>
                      <TableCell>
                        {e.status === 'activated' ? (
                          <Badge variant="success">已激活</Badge>
                        ) : (
                          <Badge variant="info">待激活</Badge>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
