// apps/admin/src/views/Packages.vue
<template>
  <div>
    <el-card style="margin-bottom: 16px;">
      <div style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
        <el-input v-model="query.keyword" placeholder="关键词 / 国家 / 描述" clearable style="width: 240px;" @keyup.enter="load" @clear="load" />
        <el-input v-model="query.countryCode" placeholder="国家代码 如 JP" clearable style="width: 160px;" @keyup.enter="load" @clear="load" />
        <el-switch v-model="query.onlyFeatured" active-text="仅显示精选" @change="load" />
        <el-button type="primary" @click="load">搜索</el-button>
        <el-button type="primary" plain @click="openAdd">添加套餐</el-button>
        <el-button type="success" @click="syncFromTiger" :loading="syncing">从 Tiger 导入</el-button>
      </div>
    </el-card>
    <el-card>
      <template #header>
        <div style="display: flex; justify-content: space-between; align-items: center;">
          <span style="font-weight: 700;">套餐列表</span>
          <el-button type="primary" @click="openAdd">
            <el-icon><Plus /></el-icon> 添加套餐
          </el-button>
        </div>
      </template>
      <el-table :data="packages" stripe>
        <el-table-column label="国家" width="160">
          <template #default="{ row }">
            <div style="display: flex; align-items: center; gap: 6px;">
              <img v-if="row.country?.flag" :src="row.country.flag" :alt="row.country?.name" style="width: 24px; height: 16px; object-fit: cover; border-radius: 2px;" />
              <span>{{ row.country?.name }}</span>
            </div>
          </template>
        </el-table-column>
        <el-table-column prop="gb" label="流量" width="80">
          <template #default="{ row }">{{ row.gb }}GB</template>
        </el-table-column>
        <el-table-column prop="days" label="有效期" width="80">
          <template #default="{ row }">{{ row.days }}天</template>
        </el-table-column>
        <el-table-column prop="price" label="价格" width="100">
          <template #default="{ row }">¥{{ row.price }}</template>
        </el-table-column>
        <el-table-column prop="type" label="类型" width="100" />
        <el-table-column prop="tag" label="标签" width="80">
          <template #default="{ row }">
            <el-tag v-if="row.tag" size="small" :color="row.tagColor" style="color: #fff;">{{ row.tag }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="network" label="网络" width="100" />
        <el-table-column label="Tiger ID" width="100">
          <template #default="{ row }">
            <span v-if="row.tigerPkgId">{{ row.tigerPkgId }}</span>
            <el-tag v-else size="small" type="info">未关联</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="160" fixed="right">
          <template #default="{ row }">
            <el-button size="small" @click="editPkg(row)">编辑</el-button>
            <el-button size="small" type="danger" @click="deletePkg(row.id)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
      <div style="display:flex;justify-content:flex-end;margin-top:16px;">
        <el-pagination
          v-model:current-page="page"
          :page-size="pageSize"
          :total="total"
          layout="total, prev, pager, next, sizes"
          :page-sizes="[10, 20, 50, 100]"
          @current-change="load"
          @size-change="onSizeChange"
        />
      </div>
    </el-card>

    <el-dialog v-model="showAdd" :title="editing ? '编辑套餐' : '添加套餐'" width="650px" @open="onDialogOpen">
      <el-form :model="form" label-width="110px">
        <el-divider content-position="left">基础信息</el-divider>
        <el-form-item label="国家代码" required>
          <el-input v-model="form.countryCode" :disabled="!!editing" placeholder="如 JP, US, GLOBAL" />
        </el-form-item>
        <el-form-item label="流量 (GB)" required>
          <el-input-number v-model="form.gb" :min="1" :max="1000" />
        </el-form-item>
        <el-form-item label="有效期 (天)" required>
          <el-input-number v-model="form.days" :min="1" :max="365" />
        </el-form-item>
        <el-form-item label="价格 (¥)" required>
          <el-input-number v-model="form.price" :min="0" :precision="2" :step="0.1" />
        </el-form-item>
        <el-form-item label="是否精选">
          <el-switch v-model="form.isFeatured" />
        </el-form-item>

        <el-divider content-position="left">套餐详情</el-divider>
        <el-form-item label="套餐名称">
          <el-input v-model="form.name" placeholder="套餐显示名称" />
        </el-form-item>
        <el-form-item label="套餐类型">
          <el-select v-model="form.type" style="width: 100%;">
            <el-option label="本地套餐" value="本地套餐" />
            <el-option label="多国通用" value="多国通用" />
            <el-option label="区域套餐" value="区域套餐" />
          </el-select>
        </el-form-item>
        <el-form-item label="网络类型">
          <el-input v-model="form.network" placeholder="如 4G/5G" />
        </el-form-item>
        <el-form-item label="速度描述">
          <el-input v-model="form.speed" placeholder="如 高速" />
        </el-form-item>
        <el-form-item label="覆盖范围">
          <el-input v-model="form.coverage" placeholder="如 日本覆盖" />
        </el-form-item>
        <el-form-item label="套餐描述">
          <el-input v-model="form.desc" type="textarea" :rows="2" placeholder="套餐详细描述" />
        </el-form-item>

        <el-divider content-position="left">标签与特性</el-divider>
        <el-form-item label="标签">
          <el-input v-model="form.tag" placeholder="如 热门、推荐" />
        </el-form-item>
        <el-form-item label="标签颜色">
          <el-color-picker v-model="form.tagColor" />
        </el-form-item>
        <el-form-item label="特性列表">
          <el-input v-model="form.features" type="textarea" :rows="2" placeholder='JSON 数组格式，如 ["特性1","特性2"]' />
        </el-form-item>
        <el-form-item label="安装步骤">
          <el-input v-model="form.installSteps" type="textarea" :rows="2" placeholder='JSON 数组格式，如 ["步骤1","步骤2"]' />
        </el-form-item>

        <el-divider content-position="left">Tiger 关联</el-divider>
        <el-form-item label="Tiger 套餐 ID">
          <el-input-number v-model="form.tigerPkgId" :min="0" placeholder="Tiger 系统中的套餐 ID" style="width: 100%;" />
        </el-form-item>
        <el-form-item label="Tiger PID">
          <el-input v-model="form.tigerPid" placeholder="Tiger 系统中的产品 ID" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showAdd = false">取消</el-button>
        <el-button type="primary" @click="savePkg" :loading="saving">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { adminApi } from '../api';

const packages = ref([]);
const showAdd = ref(false);
const editing = ref(null);
const page = ref(1);
const pageSize = ref(20);
const total = ref(0);
const syncing = ref(false);
const saving = ref(false);
const query = ref({ keyword: '', countryCode: '', onlyFeatured: false });

const defaultForm = () => ({
  countryCode: '',
  gb: 1,
  days: 7,
  price: 0,
  name: '',
  type: '本地套餐',
  network: '4G/5G',
  speed: '高速',
  coverage: '',
  tag: '',
  tagColor: '',
  desc: '',
  isFeatured: false,
  features: '[]',
  installSteps: '[]',
  tigerPkgId: null as number | null,
  tigerPid: '',
});

const form = ref(defaultForm());

const openAdd = () => {
  editing.value = null;
  form.value = defaultForm();
  showAdd.value = true;
};

const onDialogOpen = () => {
  if (!editing.value) {
    form.value = defaultForm();
  }
};

const load = async () => {
  const params: any = {
    page: page.value,
    pageSize: pageSize.value,
  };
  if (query.value.keyword) params.keyword = query.value.keyword;
  if (query.value.countryCode) params.countryCode = query.value.countryCode;
  if (query.value.onlyFeatured) params.featured = '1';
  const res = await adminApi.getPackagesPage(params);
  packages.value = res.data.data.packages || [];
  total.value = res.data.data.total || 0;
};

const onSizeChange = (size: number) => {
  pageSize.value = size;
  page.value = 1;
  load();
};

const editPkg = (row) => {
  editing.value = row;
  form.value = {
    countryCode: row.countryCode || '',
    gb: row.gb || 1,
    days: row.days || 7,
    price: row.price || 0,
    name: row.name || '',
    type: row.type || '本地套餐',
    network: row.network || '4G/5G',
    speed: row.speed || '高速',
    coverage: row.coverage || '',
    tag: row.tag || '',
    tagColor: row.tagColor || '',
    desc: row.desc || '',
    isFeatured: row.isFeatured || false,
    features: row.features || '[]',
    installSteps: row.installSteps || '[]',
    tigerPkgId: row.tigerPkgId || null,
    tigerPid: row.tigerPid || '',
  };
  showAdd.value = true;
};

const validateForm = () => {
  if (!form.value.countryCode) {
    ElMessage.warning('请输入国家代码');
    return false;
  }
  if (form.value.gb < 1) {
    ElMessage.warning('流量必须大于 0');
    return false;
  }
  if (form.value.days < 1) {
    ElMessage.warning('有效期必须大于 0');
    return false;
  }
  if (form.value.price < 0) {
    ElMessage.warning('价格不能为负数');
    return false;
  }
  // 验证 JSON 格式
  try {
    JSON.parse(form.value.features);
    JSON.parse(form.value.installSteps);
  } catch {
    ElMessage.warning('特性列表和安装步骤必须是有效的 JSON 数组格式');
    return false;
  }
  return true;
};

const savePkg = async () => {
  if (!validateForm()) return;
  
  saving.value = true;
  try {
    const data = {
      countryCode: form.value.countryCode,
      gb: form.value.gb,
      days: form.value.days,
      price: form.value.price,
      name: form.value.name || `${form.value.countryCode} ${form.value.gb}GB/${form.value.days}天`,
      type: form.value.type,
      network: form.value.network,
      speed: form.value.speed,
      coverage: form.value.coverage || `${form.value.countryCode}覆盖`,
      tag: form.value.tag || '',
      tagColor: form.value.tagColor || '',
      desc: form.value.desc || `${form.value.gb}GB 流量，${form.value.days} 天有效`,
      isFeatured: form.value.isFeatured,
      features: form.value.features,
      installSteps: form.value.installSteps,
      tigerPkgId: form.value.tigerPkgId,
      tigerPid: form.value.tigerPid || '',
    };
    if (editing.value) {
      await adminApi.updatePackage(editing.value.id, data);
    } else {
      await adminApi.createPackage(data);
    }
    ElMessage.success('保存成功');
    showAdd.value = false;
    editing.value = null;
    load();
  } catch (e: any) {
    ElMessage.error(e.response?.data?.message || '保存失败');
  } finally {
    saving.value = false;
  }
};

const deletePkg = async (id) => {
  await ElMessageBox.confirm('确定删除该套餐？', '警告', { type: 'warning' });
  await adminApi.deletePackage(id);
  ElMessage.success('已删除');
  load();
};

const syncFromTiger = async () => {
  syncing.value = true;
  try {
    const res = await adminApi.syncTigerPackages();
    if (res.data.code === 0) {
      const { matched, total, tigerTotal } = res.data.data;
      ElMessage.success(`同步成功：Tiger 共 ${tigerTotal} 个套餐，本地匹配 ${matched} 个，总计 ${total} 个`);
      load();
    } else {
      ElMessage.error(res.data.message || '同步失败');
    }
  } catch (e: any) {
    ElMessage.error(e.response?.data?.message || '同步失败');
  } finally {
    syncing.value = false;
  }
};

onMounted(load);
</script>

// apps/admin/src/app/(admin)/packages/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { Plus, Search, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { NumberField } from '@/components/NumberField';
import { EmptyState } from '@/components/EmptyState';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from '@/components/ui/pagination';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { adminApi, unwrap, getErrorMessage, type PackageItem } from '@/api';

// 套餐表单字段与 TigerESIM 创建套餐接口对齐：name / amount(GB) / valid_days / region_id / sales / package_type
interface PackageForm {
  name: string;
  countryCode: string;
  gb: number; // amount，单位 GB
  days: number; // valid_days
  price: number; // sales
}

const defaultForm: PackageForm = {
  name: '',
  countryCode: '',
  gb: 1,
  days: 7,
  price: 0,
};

export default function PackagesPage() {
  const [packages, setPackages] = useState<PackageItem[]>([]);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [syncing, setSyncing] = useState(false);

  // 筛选条件状态
  const [filter, setFilter] = useState({ keyword: '', countryCode: '', onlyFeatured: false });

  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<PackageItem | null>(null);
  const [form, setForm] = useState<PackageForm>(defaultForm);
  const [saving, setSaving] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<PackageItem | null>(null);
  // 关联了 TigerESIM 的套餐，编辑/删除时提示前往 Tiger 后台操作
  const [tigerReminder, setTigerReminder] = useState<{ name: string; action: string } | null>(null);

  const totalPages = Math.max(1, Math.ceil(total / pageSize));

  const load = async () => {
    setLoading(true);
    const params: Record<string, unknown> = { page, pageSize };
    if (filter.keyword) params.keyword = filter.keyword;
    if (filter.countryCode) params.countryCode = filter.countryCode;
    if (filter.onlyFeatured) params.featured = '1';
    try {
      const res = await adminApi.getPackagesPage(params);
      const data = unwrap<{ packages: PackageItem[]; total: number }>(res).data;
      setPackages(data.packages || []);
      setTotal(data.total || 0);
    } catch (e) {
      toast.error(getErrorMessage(e, '套餐列表加载失败'));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, pageSize]);

  const applyFilter = () => {
    setPage(1);
    load();
  };

  const openAdd = () => {
    setForm(defaultForm);
    setOpen(true);
  };

  const openEdit = (p: PackageItem) => {
    // 所有套餐均实时来自 TigerESIM，本地不支持修改，统一引导前往 Tiger 后台
    setTigerReminder({ name: `${p.country?.name || p.countryCode} ${p.gb}GB/${p.days}天`, action: '编辑' });
  };

  const save = async () => {
    if (!form.countryCode) return toast.warning('请输入国家/区域代码');
    if (form.gb < 1) return toast.warning('流量必须大于 0');
    if (form.days < 1) return toast.warning('有效期必须大于 0');
    if (form.price < 0) return toast.warning('价格不能为负数');

    setSaving(true);
    // 直调 TigerESIM 创建套餐（字段与 createPackage 接口一致）
    const data = {
      name: form.name || `${form.countryCode} ${form.gb}GB/${form.days}天`,
      countryCode: form.countryCode.toUpperCase(),
      gb: form.gb,
      days: form.days,
      price: form.price,
      package_type: 'data',
    };
    try {
      const res = await adminApi.createPackage(data);
      const body = unwrap<{ tigerPkgId: number }>(res);
      toast.success(`已通过 TigerESIM 创建真实套餐（Tiger ID: ${body.data.tigerPkgId}）`);
      setOpen(false);
      load();
    } catch (e) {
      toast.error(getErrorMessage(e, '保存失败'));
    } finally {
      setSaving(false);
    }
  };

  const confirmDelete = async () => {
    if (!deleteTarget) return;
    try {
      await adminApi.deletePackage(deleteTarget.id);
      toast.success('已删除');
      setDeleteTarget(null);
      load();
    } catch (e) {
      toast.error(getErrorMessage(e, '删除失败'));
    }
  };

  const syncFromTiger = async () => {
    setSyncing(true);
    try {
      const res = await adminApi.syncTigerPackages();
      const body = unwrap<{ matched: number; total: number; tigerTotal: number }>(res);
      if (body.code === 0) {
        toast.success(`同步成功：Tiger 共 ${body.data.tigerTotal} 个套餐，本地匹配 ${body.data.matched} 个，总计 ${body.data.total} 个`);
        load();
      } else {
        toast.error(body.message || '同步失败');
      }
    } catch (e) {
      toast.error(getErrorMessage(e, '同步失败'));
    } finally {
      setSyncing(false);
    }
  };

  return (
    <div className="animate-fade-up space-y-5">
      {/* 筛选条件卡片 —— 中文文案均以 UTF-8 硬编码 */}
      <Card className="border-transparent bg-white/70 backdrop-blur-sm">
        <CardContent className="flex flex-wrap items-end gap-3 pt-5">
          <Field label="关键词">
            <Input
              value={filter.keyword}
              onChange={(e) => setFilter({ ...filter, keyword: e.target.value })}
              onKeyDown={(e) => e.key === 'Enter' && applyFilter()}
              placeholder="关键词 / 国家 / 描述"
              className="w-56"
            />
          </Field>
          <Field label="国家代码">
            <Input
              value={filter.countryCode}
              onChange={(e) => setFilter({ ...filter, countryCode: e.target.value })}
              onKeyDown={(e) => e.key === 'Enter' && applyFilter()}
              placeholder="如 JP"
              className="w-36"
            />
          </Field>
          <div className="flex items-center gap-2 pb-2">
            <Switch
              id="onlyFeatured"
              checked={filter.onlyFeatured}
              onCheckedChange={(v) => setFilter({ ...filter, onlyFeatured: v })}
            />
            <Label htmlFor="onlyFeatured">仅显示精选</Label>
          </div>
          <Button size="sm" onClick={applyFilter}>
            <Search className="h-4 w-4" /> 搜索
          </Button>
          <div className="ml-auto flex gap-2">
            <Button size="sm" variant="outline" onClick={openAdd}>
              <Plus className="h-4 w-4" /> 添加套餐
            </Button>
            <Button size="sm" variant="secondary" onClick={syncFromTiger} disabled={syncing}>
              <RefreshCw className={syncing ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} /> 从 Tiger 导入
            </Button>
          </div>
        </CardContent>
      </Card>

      <Card className="border-transparent bg-white/70 backdrop-blur-sm">
        <CardHeader className="pb-3">
          <CardTitle className="flex items-baseline justify-between text-[15px] text-ink">
            <span>套餐列表</span>
            <span className="text-[12px] font-normal text-muted-foreground">共 {total} 条</span>
          </CardTitle>
        </CardHeader>
        <CardContent>
          {packages.length === 0 && !loading ? (
            <EmptyState title="暂无套餐" hint="可通过「从 Tiger 导入」或手动添加" />
          ) : (
            <>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>国家</TableHead>
                    <TableHead>流量</TableHead>
                    <TableHead>有效期</TableHead>
                    <TableHead>价格</TableHead>
                    <TableHead>类型</TableHead>
                    <TableHead>标签</TableHead>
                    <TableHead>网络</TableHead>
                    <TableHead>Tiger ID</TableHead>
                    <TableHead className="text-right">操作</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {packages.map((p) => (
                    <TableRow key={p.id}>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          {p.country?.flag && (
                            <img src={p.country.flag} alt={p.country?.name} className="h-4 w-6 rounded-sm object-cover" />
                          )}
                          <span className="font-medium text-ink">{p.country?.name || p.countryCode}</span>
                        </div>
                      </TableCell>
                      <TableCell>{p.gb}GB</TableCell>
                      <TableCell>{p.days}天</TableCell>
                      <TableCell className="font-medium text-emerald-700">¥{p.price}</TableCell>
                      <TableCell className="text-muted-foreground">{p.type}</TableCell>
                      <TableCell>
                        {p.tag ? (
                          <span
                            className="inline-flex rounded-full px-2 py-0.5 text-[11px] font-medium text-white"
                            style={{ background: p.tagColor || '#6f8f8b' }}
                          >
                            {p.tag}
                          </span>
                        ) : (
                          <span className="text-muted-foreground/50">—</span>
                        )}
                      </TableCell>
                      <TableCell>{p.network}</TableCell>
                      <TableCell>
                        {p.tigerPkgId ? (
                          <span className="font-mono text-[12.5px]">{p.tigerPkgId}</span>
                        ) : (
                          <span className="rounded-full bg-muted px-2 py-0.5 text-[11px] text-muted-foreground">未关联</span>
                        )}
                      </TableCell>
                      <TableCell align="right">
                        <Button size="sm" variant="ghost" onClick={() => openEdit(p)}>
                          编辑
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          className="text-destructive hover:text-destructive"
                          onClick={() =>
                            p.tigerPkgId
                              ? setTigerReminder({ name: `${p.country?.name || p.countryCode} ${p.gb}GB/${p.days}天`, action: '删除' })
                              : setDeleteTarget(p)
                          }
                        >
                          删除
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>

              <div className="mt-4 flex items-center justify-between">
                <div className="flex items-center gap-2 text-[12px] text-muted-foreground">
                  每页
                  <select
                    className="h-8 rounded-md border border-input bg-background px-2 text-[12px]"
                    value={pageSize}
                    onChange={(e) => {
                      setPageSize(Number(e.target.value));
                      setPage(1);
                    }}
                  >
                    {[10, 20, 50, 100].map((s) => (
                      <option key={s} value={s}>
                        {s}
                      </option>
                    ))}
                  </select>
                  条
                </div>
                <Pagination>
                  <PaginationContent>
                    <PaginationItem>
                      <PaginationPrevious
                        onClick={() => setPage((p) => Math.max(1, p - 1))}
                        className={page <= 1 ? 'pointer-events-none opacity-50' : ''}
                      />
                    </PaginationItem>
                    {Array.from({ length: totalPages }, (_, i) => i + 1)
                      .filter((n) => Math.abs(n - page) <= 2 || n === 1 || n === totalPages)
                      .map((n, idx, arr) => {
                        if (idx > 0 && n - arr[idx - 1] > 1) {
                          return (
                            <span key={`e-${n}`} className="px-1 text-muted-foreground">
                              …
                            </span>
                          );
                        }
                        return (
                          <PaginationItem key={n}>
                            <PaginationLink isActive={n === page} onClick={() => setPage(n)}>
                              {n}
                            </PaginationLink>
                          </PaginationItem>
                        );
                      })}
                    <PaginationItem>
                      <PaginationNext
                        onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                        className={page >= totalPages ? 'pointer-events-none opacity-50' : ''}
                      />
                    </PaginationItem>
                  </PaginationContent>
                </Pagination>
              </div>
            </>
          )}
        </CardContent>
      </Card>

      {/* 添加 / 编辑弹窗 */}
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-h-[88vh] max-w-2xl overflow-y-auto">
          <DialogHeader>
            <DialogTitle>添加套餐（直调 TigerESIM 创建）</DialogTitle>
          </DialogHeader>

          <div className="rounded-lg border border-dashed bg-muted/40 px-4 py-3 text-[12px] text-muted-foreground">
            套餐数据以 TigerESIM 为准，创建后将实时生效，本地不存储套餐数据。
          </div>

          <Section title="Tiger 套餐信息" />
          <div className="grid grid-cols-2 gap-4">
            <Field label="套餐名称">
              <Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="如 Japan 1GB 30Days" />
            </Field>
            <Field label="所属国家/区域代码">
              <Input value={form.countryCode} onChange={(e) => setForm({ ...form, countryCode: e.target.value })} placeholder="如 JP、US、GLOBAL" />
            </Field>
            <Field label="容量 (GB)">
              <NumberField value={form.gb} onChange={(v) => setForm({ ...form, gb: v })} min={1} max={1000} />
            </Field>
            <Field label="有效期 (天)">
              <NumberField value={form.days} onChange={(v) => setForm({ ...form, days: v })} min={1} max={365} />
            </Field>
            <Field label="售价 (¥)">
              <NumberField value={form.price} onChange={(v) => setForm({ ...form, price: v })} min={0} precision={2} step={0.1} />
            </Field>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setOpen(false)}>
              取消
            </Button>
            <Button onClick={save} disabled={saving}>
              {saving ? '创建中…' : '创建套餐'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* 删除确认 */}
      <AlertDialog open={!!deleteTarget} onOpenChange={(o) => !o && setDeleteTarget(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>确认删除该套餐？</AlertDialogTitle>
            <AlertDialogDescription>
              将删除「{deleteTarget?.country?.name || deleteTarget?.countryCode} {deleteTarget?.gb}GB / {deleteTarget?.days}天」，此操作不可撤销。
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>取消</AlertDialogCancel>
            <AlertDialogAction className="bg-destructive hover:bg-destructive/90" onClick={confirmDelete}>
              确认删除
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Tiger 关联套餐：编辑/删除提醒，需前往 TigerESIM 后台操作 */}
      <AlertDialog open={!!tigerReminder} onOpenChange={(o) => !o && setTigerReminder(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>无法在本地上{tigerReminder?.action === '编辑' ? '修改' : '删除'}该套餐</AlertDialogTitle>
            <AlertDialogDescription>
              「{tigerReminder?.name}」来自 TigerESIM，套餐数据以 TigerESIM 后台为准。
              <br />
              <br />
              由于 TigerESIM 仅提供新增套餐接口，不提供本地{tigerReminder?.action === '编辑' ? '修改/删除' : '删除'}能力，请前往{' '}
              <span className="font-medium text-ink">TigerESIM 管理后台</span> 完成{tigerReminder?.action === '编辑' ? '修改' : '删除'}操作，
              再回到本页点击「从 Tiger 导入」同步数据。
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogAction>知道了</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="space-y-1.5">
      <Label className="text-[12.5px] text-muted-foreground">{label}</Label>
      {children}
    </div>
  );
}

function Section({ title }: { title: string }) {
  return (
    <div className="mt-1 flex items-center gap-3">
      <span className="text-[13px] font-semibold text-ink">{title}</span>
      <span className="h-px flex-1 bg-border" />
    </div>
  );
}
