// apps/admin/src/app/(admin)/tiger-sync/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { RefreshCw, Globe, Package, Database, GitMerge } from 'lucide-react';
import { toast } from 'sonner';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { adminApi, unwrap, getErrorMessage, type TigerStatus } from '@/api';

interface SyncResult {
  message?: string;
  regionsSynced?: number;
  packagesSynced?: number;
  packageTotal?: number;
  cardsCount?: number;
}

export default function TigerSyncPage() {
  const [status, setStatus] = useState<TigerStatus>({});
  const [errorMsg, setErrorMsg] = useState('');
  const [result, setResult] = useState<SyncResult | null>(null);
  const [busy, setBusy] = useState<string | null>(null);

  const load = async () => {
    try {
      const res = await adminApi.getTigerStatus();
      setStatus(unwrap<TigerStatus>(res).data);
      setErrorMsg('');
    } catch (e) {
      setErrorMsg(getErrorMessage(e, '获取 Tiger 状态失败'));
    }
  };

  useEffect(() => {
    load();
  }, []);

  const run = async (key: 'all' | 'regions' | 'packages') => {
    setBusy(key);
    setErrorMsg('');
    try {
      const fn =
        key === 'all' ? adminApi.syncTigerAll : key === 'regions' ? adminApi.syncTigerRegions : adminApi.syncTigerPackages;
      const res = await fn();
      const body = unwrap<SyncResult>(res);
      if (body.code === 0) {
        setResult(body.data);
        toast.success('同步成功');
        load();
      } else {
        setErrorMsg(body.message || '同步失败');
      }
    } catch (e) {
      setErrorMsg(getErrorMessage(e, '同步失败'));
    } finally {
      setBusy(null);
    }
  };

  const rows: { label: string; value: React.ReactNode }[] = [
    { label: 'API 地址', value: status.baseUrl || '-' },
    { label: '连接模式', value: status.mode === 'tiger' ? 'Tiger 模式' : '模拟模式' },
    { label: '国家/地区', value: `${status.countryCount ?? 0} 个` },
    { label: '套餐总数', value: `${status.packageCount ?? 0} 个` },
    { label: 'ICCID 池', value: `${status.iccidPoolSize ?? 0} 个` },
    {
      label: '同步状态',
      value: status.configured ? (
        <Badge variant={status.synced ? 'success' : 'warning'}>{status.synced ? '已同步' : '未同步'}</Badge>
      ) : (
        <Badge variant="destructive">未连接</Badge>
      ),
    },
  ];

  const actions = [
    { key: 'all' as const, label: '全量同步所有数据', primary: true, icon: <RefreshCw size={16} /> },
    { key: 'regions' as const, label: '同步国家/地区', primary: false, icon: <Globe size={16} /> },
    { key: 'packages' as const, label: '同步套餐', primary: false, icon: <Package size={16} /> },
  ];

  return (
    <div className="animate-fade-up grid gap-5 lg:grid-cols-3">
      <Card className="panel-card lg:col-span-2">
        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-3">
          <div className="flex items-center gap-2">
            <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <Database size={16} />
            </span>
            <CardTitle className="text-[15px] text-ink">Tiger 同步状态</CardTitle>
          </div>
          {status.configured ? <Badge variant="success">已连接 Tiger</Badge> : <Badge variant="destructive">未连接</Badge>}
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 gap-x-8 gap-y-4">
            {rows.map((r) => (
              <div key={r.label} className="flex items-center justify-between border-b border-dashed border-border/70 pb-2 text-[13.5px]">
                <span className="text-muted-foreground">{r.label}</span>
                <span className="font-medium text-ink">{r.value}</span>
              </div>
            ))}
          </div>

          <Separator className="my-5" />

          <div className="flex flex-wrap gap-2">
            {actions.map((a) => (
              <Button
                key={a.key}
                variant={a.primary ? 'default' : 'outline'}
                onClick={() => run(a.key)}
                disabled={busy !== null}
              >
                <span className={busy === a.key ? 'animate-spin' : ''}>{a.icon}</span>
                {busy === a.key ? '同步中…' : a.label}
              </Button>
            ))}
          </div>

          {result && (
            <div className="mt-4 grid grid-cols-4 gap-3">
              <MiniStat label="新增国家" value={result.regionsSynced ?? 0} />
              <MiniStat label="新增套餐" value={result.packagesSynced ?? 0} />
              <MiniStat label="套餐总数" value={result.packageTotal ?? 0} />
              <MiniStat label="卡片总数" value={result.cardsCount ?? 0} />
            </div>
          )}

          {errorMsg && (
            <div className="mt-4 flex items-center gap-2 rounded-lg border border-destructive/30 bg-destructive/5 px-3 py-2.5 text-[13px] text-destructive">
              <GitMerge size={15} /> {errorMsg}
            </div>
          )}
        </CardContent>
      </Card>

      <Card className="h-fit panel-card">
        <CardHeader className="pb-2">
          <CardTitle className="text-[15px] text-ink">说明</CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="list-disc space-y-2 pl-4 text-[13px] leading-relaxed text-muted-foreground">
            <li>从 Tiger eSIM 合作伙伴平台同步国家/地区、套餐数据</li>
            <li>同步后会自动创建或更新本地数据库中的套餐信息</li>
            <li>套餐价格以 Tiger API 返回的 USD 价格为准</li>
            <li>全量同步会先同步国家，再同步套餐</li>
            <li>建议在套餐变动时手动触发同步</li>
          </ul>
        </CardContent>
      </Card>
    </div>
  );
}

function MiniStat({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-xl border border-border/70 bg-muted/40 px-3 py-3 text-center">
      <div className="text-xl font-bold text-ink">{value}</div>
      <div className="mt-0.5 text-[12px] text-muted-foreground">{label}</div>
    </div>
  );
}

// apps/admin/src/views/TigerSync.vue
<template>
  <div class="tiger-sync">
    <el-row :gutter="20">
      <el-col :span="16">
        <el-card class="status-card">
          <template #header>
            <div class="card-head">
              <span style="font-weight: 700;">Tiger 同步状态</span>
              <el-tag :type="status.configured ? 'success' : 'danger'">
                {{ status.configured ? '已连接 Tiger' : '未连接' }}
              </el-tag>
            </div>
          </template>

          <el-descriptions :column="2" border>
            <el-descriptions-item label="API 地址">{{ status.baseUrl || '-' }}</el-descriptions-item>
            <el-descriptions-item label="连接模式">{{ status.mode === 'tiger' ? 'Tiger 模式' : '模拟模式' }}</el-descriptions-item>
            <el-descriptions-item label="国家/地区">
              <span>{{ status.countryCount || 0 }} 个</span>
            </el-descriptions-item>
            <el-descriptions-item label="套餐总数">
              <span>{{ status.packageCount || 0 }} 个</span>
            </el-descriptions-item>
            <el-descriptions-item label="ICCID 池">
              <span>{{ status.iccidPoolSize || 0 }} 个</span>
            </el-descriptions-item>
            <el-descriptions-item label="同步状态">
              <el-tag :type="status.synced ? 'success' : 'info'" size="small">
                {{ status.synced ? '已同步' : '未同步' }}
              </el-tag>
            </el-descriptions-item>
          </el-descriptions>

          <div class="actions" style="margin-top: 20px;">
            <el-button type="primary" :loading="syncingAll" @click="syncAll">
              全量同步所有数据
            </el-button>
            <el-button :loading="syncingRegions" @click="syncRegions">同步国家/地区</el-button>
            <el-button :loading="syncingPkgs" @click="syncPackages">同步套餐</el-button>
          </div>
          <div v-if="lastResult" style="margin-top: 16px;">
            <el-alert
              :title="lastResult.message"
              type="success"
              :closable="false"
              show-icon
              style="margin-bottom: 8px;"
            />
            <el-descriptions :column="3" size="small" border>
              <el-descriptions-item label="新增">{{ lastResult.regionsSynced || 0 }}</el-descriptions-item>
              <el-descriptions-item label="套餐">{{ lastResult.packagesSynced || 0 }}</el-descriptions-item>
              <el-descriptions-item label="套餐总数">{{ lastResult.packageTotal || 0 }}</el-descriptions-item>
            </el-descriptions>
          </div>
          <div v-if="errorMsg" style="margin-top: 16px;">
            <el-alert :title="errorMsg" type="error" :closable="false" show-icon />
          </div>
        </el-card>
      </el-col>
      <el-col :span="8">
        <el-card>
          <template #header><span style="font-weight: 700;">说明</span></template>
          <ul style="line-height: 1.9; padding-left: 18px; color: #5B7A95;">
            <li>从 Tiger eSIM 合作伙伴平台同步国家/地区、套餐数据</li>
            <li>同步后会自动创建或更新本地数据库中的套餐信息</li>
            <li>套餐价格以 Tiger API 返回的 USD 价格为准</li>
            <li>全量同步会先同步国家，再同步套餐</li>
            <li>建议在套餐变动时手动触发同步</li>
          </ul>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { ElMessage } from 'element-plus';
import { adminApi } from '../api';

const status = ref<any>({});
const errorMsg = ref('');
const lastResult = ref<any>(null);
const syncingAll = ref(false);
const syncingRegions = ref(false);
const syncingPkgs = ref(false);

async function load() {
  try {
    const res = await adminApi.getTigerStatus();
    status.value = res.data.data || {};
  } catch (e: any) {
    errorMsg.value = e?.response?.data?.message || '获取 Tiger 状态失败';
  }
}

async function syncAll() {
  syncingAll.value = true;
  errorMsg.value = '';
  try {
    const res = await adminApi.syncTigerAll();
    if (res.data.code === 0) {
      lastResult.value = res.data.data;
      ElMessage.success('同步成功');
      load();
    } else {
      errorMsg.value = res.data.message;
    }
  } catch (e: any) {
    errorMsg.value = e?.response?.data?.message || '同步失败';
  } finally {
    syncingAll.value = false;
  }
}

async function syncRegions() {
  syncingRegions.value = true;
  errorMsg.value = '';
  try {
    const res = await adminApi.syncTigerRegions();
    if (res.data.code === 0) {
      lastResult.value = res.data.data;
      ElMessage.success('同步成功');
      load();
    } else {
      errorMsg.value = res.data.message;
    }
  } catch (e: any) {
    errorMsg.value = e?.response?.data?.message || '同步失败';
  } finally {
    syncingRegions.value = false;
  }
}

async function syncPackages() {
  syncingPkgs.value = true;
  errorMsg.value = '';
  try {
    const res = await adminApi.syncTigerPackages();
    if (res.data.code === 0) {
      lastResult.value = res.data.data;
      ElMessage.success('同步成功');
      load();
    } else {
      errorMsg.value = res.data.message;
    }
  } catch (e: any) {
    errorMsg.value = e?.response?.data?.message || '同步失败';
  } finally {
    syncingPkgs.value = false;
  }
}

onMounted(load);
</script>

<style scoped>
.card-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
</style>
